name: Basic Workflow Dispatch Test
on:
    workflow_dispatch:
        inputs:
            data:
                type: string

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - run: echo "output from workflow dispatch test action"
            - run: echo ${{ github.event.inputs.data }}

